In [2]:
# load the libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
output_width = 1000
#output_width = 80 #//*** Normal Output width
pd.set_option("display.width", output_width)
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [11]:
housing_data_org = pd.read_csv("../../data/raw/dsc630_project/train.csv",sep=",")

In [12]:
# Load the data into a dataframe
housing_modeling_org = pd.read_csv("../../data/processed/House_Prediction_upd.csv",sep=",")

In [21]:
# Checking the info on the dataframe for the training set
# This shows the number of columns with the data types 
# float64(3), int64(35), object(43)
housing_modeling_org.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 56 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   MSZoning       1460 non-null   object
 2   LotFrontage    1460 non-null   float64
 3   LotArea        1460 non-null   int64
 4   Street         1460 non-null   object
 5   LotShape       1460 non-null   object
 6   LandContour    1460 non-null   object
 7   LotConfig      1460 non-null   object
 8   LandSlope      1460 non-null   object
 9   Neighborhood   1460 non-null   object
 10  Condition1     1460 non-null   object
 11  Condition2     1460 non-null   object
 12  BldgType       1460 non-null   object
 13  HouseStyle     1460 non-null   object
 14  OverallQual    1460 non-null   int64
 15  OverallCond    1460 non-null   int64
 16  YearBuilt      1460 non-null   int64
 17  YearRemodAdd   1460 non-null   int64
 18  RoofStyle      1460 non-null   object
 19  RoofMatl       1460 non-null   object
 20  Exterior1st    1460 non-null   object
 21  Exterior2nd    1460 non-null   object
 22  MasVnrType     1460 non-null   object
 23  MasVnrArea     1460 non-null   object
 24  ExterQual      1460 non-null   object
 25  ExterCond      1460 non-null   object
 26  Foundation     1460 non-null   object
 27  BsmtQual       1460 non-null   object
 28  BsmtCond       1460 non-null   object
 29  BsmtExposure   1460 non-null   object
 30  BsmtFinType1   1460 non-null   object
 31  BsmtFinType2   1460 non-null   object
 32  HeatingQC      1460 non-null   object
 33  CentralAir     1460 non-null   object
 34  BedroomAbvGr   1460 non-null   int64
 35  KitchenAbvGr   1460 non-null   int64
 36  KitchenQual    1460 non-null   object
 37  TotRmsAbvGrd   1460 non-null   int64
 38  Functional     1460 non-null   object
 39  Fireplaces     1460 non-null   int64
 40  FireplaceQu    1460 non-null   object
 41  GarageType     1460 non-null   object
 42  GarageFinish   1460 non-null   object
 43  GarageCars     1460 non-null   int64
 44  GarageArea     1460 non-null   int64
 45  GarageCond     1460 non-null   object
 46  PavedDrive     1460 non-null   object
 47  PoolArea       1460 non-null   int64
 48  MoSold         1460 non-null   int64
 49  YrSold         1460 non-null   int64
 50  SaleCondition  1460 non-null   object
 51  TotalSF        1460 non-null   int64
 52  TotalBath      1460 non-null   int64
 53  TotalPorchSF   1460 non-null   int64
 54  TotalBathSum   1460 non-null   float64
 55  SalePrice      1460 non-null   int64
dtypes: float64(2), int64(19), object(35)
memory usage: 638.9+ KB

In [14]:
# store columns with specific data type
integer_columns = housing_modeling_org.select_dtypes(include=['int64']).columns
float_columns = housing_modeling_org.select_dtypes(include=['float64']).columns
object_columns = housing_modeling_org.select_dtypes(include=['object']).columns
  
# display columns
print('\nint64 columns:\n',integer_columns)
print('\nfloat64 columns:\n',float_columns)
print('\nobject columns:\n',object_columns)

int64 columns:
 Index(['MSSubClass', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageCars', 'GarageArea', 'PoolArea', 'MoSold', 'YrSold', 'TotalSF', 'TotalBath', 'TotalPorchSF'], dtype='object')

float64 columns:
 Index(['LotFrontage'], dtype='object')

object columns:
 Index(['MSZoning', 'Street', 'LotShape', 'LandContour', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'HeatingQC', 'CentralAir', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageCond', 'PavedDrive', 'SaleCondition'], dtype='object')

In [15]:
# housing_final = housing_train[col_list]
housing_modeling_org['TotalBath'].value_counts()

2    612
1    469
3    353
4     23
0      3
Name: TotalBath, dtype: int64

In [19]:
housing_modeling_org['TotalBathSum'].value_counts()

2.0    456
2.5    295
1.0    228
3.0    186
3.5    144
1.5    129
4.0     13
4.5      7
6.0      1
5.0      1
Name: TotalBathSum, dtype: int64

In [17]:
housing_data_org.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [18]:
housing_modeling_org["TotalBathSum"] = (
    housing_data_org["FullBath"] + 0.5 * housing_data_org["HalfBath"] + housing_data_org["BsmtFullBath"] + 0.5 * housing_data_org["BsmtHalfBath"]
)

In [20]:
# Adding the target column to the final dataset
housing_modeling_org['SalePrice']=housing_data_org['SalePrice']

In [22]:
# Saving the feature set till now
housing_modeling_org.to_csv("housing_modeling_org.csv")

### Preparing data for modeling

In [22]:
# Checking to see if any of the columns has null values
# There are no columns with null values

housing_modeling_org.isnull().sum()

MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
Street           0
LotShape         0
LandContour      0
LotConfig        0
LandSlope        0
Neighborhood     0
Condition1       0
Condition2       0
BldgType         0
HouseStyle       0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
RoofStyle        0
RoofMatl         0
Exterior1st      0
Exterior2nd      0
MasVnrType       0
MasVnrArea       0
ExterQual        0
ExterCond        0
Foundation       0
BsmtQual         0
BsmtCond         0
BsmtExposure     0
BsmtFinType1     0
BsmtFinType2     0
HeatingQC        0
CentralAir       0
BedroomAbvGr     0
KitchenAbvGr     0
KitchenQual      0
TotRmsAbvGrd     0
Functional       0
Fireplaces       0
FireplaceQu      0
GarageType       0
GarageFinish     0
GarageCars       0
GarageArea       0
GarageCond       0
PavedDrive       0
PoolArea         0
MoSold           0
YrSold           0
SaleCondition    0
TotalSF          0
TotalBath        0
TotalPorchSF     0
TotalBathSum     0
dtype: int64

In [23]:
# housing_shared_sub=housing_shared[['MSSubClass','MSZoning','LotShape','ExterCond']]
housing_shared_sub=housing_shared.loc[:, ('MSSubClass','MSZoning','LotShape','ExterCond')]

In [24]:
housing_shared_sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MSSubClass  1460 non-null   int64
 1   MSZoning    1460 non-null   object
 2   LotShape    1460 non-null   object
 3   ExterCond   1460 non-null   object
dtypes: int64(1), object(3)
memory usage: 45.8+ KB

In [23]:
housing_modeling_object = housing_modeling_org.loc[:,object_columns]

In [24]:
print("Shape of the new dataframe with object columns:", housing_modeling_object.shape)

Shape of the new dataframe with object columns: (1460, 35)

In [25]:
# Looking at the column info for the object dataframe
housing_modeling_object.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 35 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSZoning       1460 non-null   object
 1   Street         1460 non-null   object
 2   LotShape       1460 non-null   object
 3   LandContour    1460 non-null   object
 4   LotConfig      1460 non-null   object
 5   LandSlope      1460 non-null   object
 6   Neighborhood   1460 non-null   object
 7   Condition1     1460 non-null   object
 8   Condition2     1460 non-null   object
 9   BldgType       1460 non-null   object
 10  HouseStyle     1460 non-null   object
 11  RoofStyle      1460 non-null   object
 12  RoofMatl       1460 non-null   object
 13  Exterior1st    1460 non-null   object
 14  Exterior2nd    1460 non-null   object
 15  MasVnrType     1460 non-null   object
 16  MasVnrArea     1460 non-null   object
 17  ExterQual      1460 non-null   object
 18  ExterCond      1460 non-null   object
 19  Foundation     1460 non-null   object
 20  BsmtQual       1460 non-null   object
 21  BsmtCond       1460 non-null   object
 22  BsmtExposure   1460 non-null   object
 23  BsmtFinType1   1460 non-null   object
 24  BsmtFinType2   1460 non-null   object
 25  HeatingQC      1460 non-null   object
 26  CentralAir     1460 non-null   object
 27  KitchenQual    1460 non-null   object
 28  Functional     1460 non-null   object
 29  FireplaceQu    1460 non-null   object
 30  GarageType     1460 non-null   object
 31  GarageFinish   1460 non-null   object
 32  GarageCond     1460 non-null   object
 33  PavedDrive     1460 non-null   object
 34  SaleCondition  1460 non-null   object
dtypes: object(35)
memory usage: 399.3+ KB

In [26]:
# Applying label encoder one column at a time
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
lotshape_encoded = le.fit_transform(housing_shared_sub['LotShape'])
ExterCond_encoded = le.fit_transform(housing_shared_sub['ExterCond'])
# type(lotshape_encoded)

housing_shared_sub['lotshape_encoded'] = lotshape_encoded
housing_shared_sub['ExterCond_encoded'] = ExterCond_encoded

NameError: name 'housing_shared_sub' is not defined

In [27]:
#applying label encoder to the entire object dataframe
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
housing_modeling_object = housing_modeling_object.apply(le.fit_transform)

In [28]:
housing_modeling_org.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 56 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   MSZoning       1460 non-null   object
 2   LotFrontage    1460 non-null   float64
 3   LotArea        1460 non-null   int64
 4   Street         1460 non-null   object
 5   LotShape       1460 non-null   object
 6   LandContour    1460 non-null   object
 7   LotConfig      1460 non-null   object
 8   LandSlope      1460 non-null   object
 9   Neighborhood   1460 non-null   object
 10  Condition1     1460 non-null   object
 11  Condition2     1460 non-null   object
 12  BldgType       1460 non-null   object
 13  HouseStyle     1460 non-null   object
 14  OverallQual    1460 non-null   int64
 15  OverallCond    1460 non-null   int64
 16  YearBuilt      1460 non-null   int64
 17  YearRemodAdd   1460 non-null   int64
 18  RoofStyle      1460 non-null   object
 19  RoofMatl       1460 non-null   object
 20  Exterior1st    1460 non-null   object
 21  Exterior2nd    1460 non-null   object
 22  MasVnrType     1460 non-null   object
 23  MasVnrArea     1460 non-null   object
 24  ExterQual      1460 non-null   object
 25  ExterCond      1460 non-null   object
 26  Foundation     1460 non-null   object
 27  BsmtQual       1460 non-null   object
 28  BsmtCond       1460 non-null   object
 29  BsmtExposure   1460 non-null   object
 30  BsmtFinType1   1460 non-null   object
 31  BsmtFinType2   1460 non-null   object
 32  HeatingQC      1460 non-null   object
 33  CentralAir     1460 non-null   object
 34  BedroomAbvGr   1460 non-null   int64
 35  KitchenAbvGr   1460 non-null   int64
 36  KitchenQual    1460 non-null   object
 37  TotRmsAbvGrd   1460 non-null   int64
 38  Functional     1460 non-null   object
 39  Fireplaces     1460 non-null   int64
 40  FireplaceQu    1460 non-null   object
 41  GarageType     1460 non-null   object
 42  GarageFinish   1460 non-null   object
 43  GarageCars     1460 non-null   int64
 44  GarageArea     1460 non-null   int64
 45  GarageCond     1460 non-null   object
 46  PavedDrive     1460 non-null   object
 47  PoolArea       1460 non-null   int64
 48  MoSold         1460 non-null   int64
 49  YrSold         1460 non-null   int64
 50  SaleCondition  1460 non-null   object
 51  TotalSF        1460 non-null   int64
 52  TotalBath      1460 non-null   int64
 53  TotalPorchSF   1460 non-null   int64
 54  TotalBathSum   1460 non-null   float64
 55  SalePrice      1460 non-null   int64
dtypes: float64(2), int64(19), object(35)
memory usage: 638.9+ KB

https://www.pluralsight.com/guides/preparing-data-modeling-scikit-learn

https://codefires.com/how-convert-categorical-data-numerical-data-python/

In [36]:
# housing_modeling_object['MSZoning'].value_counts()
housing_modeling_object['GarageCond'].value_counts()

4    1407
1      35
2       9
3       7
0       2
Name: GarageCond, dtype: int64

In [37]:
#housing_modeling_org['MSZoning'].value_counts()
housing_modeling_org['GarageCond'].value_counts()

TA    1407
Fa      35
Gd       9
Po       7
Ex       2
Name: GarageCond, dtype: int64

In [29]:
# This will convert only the categorical columns in the originaldataframe
# all categorical columns are in the list object "object_columns"
# The following for loop will convert only if the column is in the object list
for col in housing_modeling_org[object_columns]:
    housing_modeling_org[col]=le.fit_transform(housing_modeling_org[col])

In [30]:
housing_modeling_org['GarageCond'].value_counts()

4    1407
1      35
2       9
3       7
0       2
Name: GarageCond, dtype: int64

In [31]:
# Saving the feature set till now converted to numeric
housing_modeling_org.to_csv("housing_modeling_org_le.csv")

In [46]:
housing_modeling_org

AttributeError: 'DataFrame' object has no attribute 'show'

### Create Dataframes and load the data for the Models

In [33]:
import numpy as np
from sklearn.utils import shuffle

In [34]:
# Load the data
# The dataframe df1 holds the cleaned data with all columns casted as integers
df1= pd.read_csv("housing_modeling_org_le.csv",sep=",")

In [35]:
random_state = np.random.RandomState(42)

In [36]:
df1 = shuffle(df1, random_state=random_state)

In [40]:
df1.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1460 entries, 892 to 1126
Columns: 57 entries, Unnamed: 0 to SalePrice
dtypes: float64(2), int64(55)
memory usage: 661.6 KB

In [38]:
df1.head()

      Unnamed: 0  MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  LandContour  LotConfig  LandSlope  Neighborhood  Condition1  Condition2  BldgType  HouseStyle  OverallQual  OverallCond  YearBuilt  YearRemodAdd  RoofStyle  RoofMatl  Exterior1st  Exterior2nd  MasVnrType  MasVnrArea  ExterQual  ExterCond  Foundation  BsmtQual  BsmtCond  BsmtExposure  BsmtFinType1  BsmtFinType2  HeatingQC  CentralAir  BedroomAbvGr  KitchenAbvGr  KitchenQual  TotRmsAbvGrd  Functional  Fireplaces  FireplaceQu  GarageType  GarageFinish  GarageCars  GarageArea  GarageCond  PavedDrive  PoolArea  MoSold  YrSold  SaleCondition  TotalSF  TotalBath  TotalPorchSF  TotalBathSum  SalePrice
892          892          20         3         70.0     8414       1         3            3          4          0            19           2           2         0           2            6            8       1963          2003          3         1            6            6           2           2          3          4           1         3         3             3             2             5          4           1             3             1            3             6           6           0            2           1             1           1         264           4           2         0       2    2006              4     2127          1             0           1.5     154500
1105        1105          60         3         98.0    12256       1         0            3          0          0            15           2           2         0           5            8            5       1994          1995          1         1            6            6           1           1          2          4           2         0         3             0             2             5          0           1             3             1            2             9           6           2            4           1             1           2         712           4           2         0       4    2010              4     4085          3            32           3.5     325000
413          413          30         4         56.0     8960       1         3            3          4          0            17           0           2         0           2            5            6       1927          1950          1         1           14           15           2           2          3          4           1         3         3             3             5             5          2           1             2             1            3             5           6           1            2           5             2           2         360           4           2         0       3    2010              4     2036          1           130           1.0     115000
522          522          50         4         50.0     5000       1         3            3          0          0             3           1           2         0           0            6            7       1947          1950          1         1            5            5           2           2          3          2           1         3         3             3             0             5          0           1             3             1            3             7           6           2            2           5             2           2         420           4           2         0      10    2006              4     2668          2            60           2.0     159000
1036        1036          20         3         89.0    12898       1         0            1          4          0            23           2           2         0           2            9            5       2007          2008          3         1           12           13           3           3          2          4           2         0         3             1             2             5          0           1             2             1            0             6           6           1            0           1             0           3         912           4           2         0       9    2009              4     3240          2             0           3.0     315500

In [8]:
# Obtain the numpy arrays
X1 = df1.drop(columns="SalePrice").values
y1 = df1["SalePrice"].values

NameError: name 'df1' is not defined

In [42]:
X1.shape

(1460, 56)

In [43]:
y1

array([154500, 325000, 115000, ..., 115000, 189950, 174000])

### Creating Models

# Re Usable Components
# Define a function to run k-fold cross validation to obtain unbiased estimators for the following scores/errors
## Bias
## Mean Absolute Error
## Maximum Deviation 
## R2
## Root Mean Squared Error

In [4]:
from tqdm import tqdm as progress_bar
from sklearn.model_selection import GridSearchCV, KFold
from sklearn.metrics import (
    mean_squared_error,
    r2_score,
)

def cross_validation(X, y, *, model, k=10, log=False, desc=None):
    """Perform a k-fold cross validation."""
    # bias, mae, max_dev, r2, rmse = [], [], [], [], []
    r2, rmse = [], []
    # Iterate over the k folds.
    for train, test in progress_bar(KFold(n_splits=k).split(X), desc=desc, total=k):
        model.fit(X[train], y[train])
        y_pred = model.predict(X[test])
        # If the sales price is provided on a log scale,
        # take the exponent first so that scores and
        # errors are comparable to the non-logged counterparts.
        if log:
            y_true, y_pred = np.exp(y[test]), np.exp(y_pred) 
        else:
            y_true, y_pred = y[test], y_pred
        # Collect the scores/errors for each fold.
        r2.append(r2_score(y_true, y_pred))
        rmse.append(mean_squared_error(y_true, y_pred))
    # Round for convenience.
    return {
        "r2": np.round(np.mean(r2), 3),
        "rmse": np.round(np.sqrt(np.mean(rmse))),
    }

In [5]:
## Using dictionary to store all the results
results = {}

In [6]:
## Linear Regression
## A plain OLS regression model 
from sklearn.linear_model import LinearRegression
lm = LinearRegression()

In [7]:
results[('lm','o')] = cross_validation(X1, y1, model=lm)
results[('lm','o')]

NameError: name 'X1' is not defined

In [2]:
# Linear Regression
from sklearn.linear_model import LinearRegression
lm = LinearRegression()

In [3]:
# Fit the linear model
model = lm.fit(X1,y1)

NameError: name 'X1' is not defined

In [1]:
model.score(X1,y1)

NameError: name 'model' is not defined

In [63]:
# View the Bias or intercept
model.intercept_

1582449.0915825851

In [64]:
# View the feature coefficients
model.coef_

array([-2.36230292e+00, -5.66855793e+01, -5.61821076e+02, -1.17828658e+02,
        3.67153249e-01,  3.01338097e+04, -1.06297290e+03,  3.09407782e+03,
       -1.09193762e+02,  8.02530760e+03,  4.06139464e+02, -1.09448398e+03,
       -8.46563092e+03, -3.36815709e+03, -6.59009589e+02,  1.11526902e+04,
        4.91936736e+03,  7.36777405e+01, -1.95469838e+00,  3.48968617e+03,
        6.09200245e+03, -1.15428277e+03,  4.88642520e+02,  4.35917527e+02,
        4.35917527e+02, -9.42380971e+03,  2.63355164e+02,  3.35685533e+03,
       -9.46056056e+03,  2.44504079e+03, -3.40793437e+03, -1.28007425e+03,
        3.02377737e+02, -5.54738010e+02,  3.14432682e+01, -3.69441424e+03,
       -1.61889587e+04, -8.73099359e+03,  6.19031795e+03,  3.25725407e+03,
        7.94344140e+03, -2.27985585e+03,  2.14649678e+02, -5.77857149e+02,
        9.89008416e+03,  3.89076316e+00,  2.57636022e+03,  1.69852468e+03,
       -7.04722232e+00, -1.02042028e+02, -8.69065405e+02,  2.16465209e+03,
        2.38384486e+01,  1.97592645e+03,  6.17991580e+00,  8.79989330e+03])

In [71]:
y1[5]

75500

In [66]:
X1[1]

array([1.1050e+03, 6.0000e+01, 3.0000e+00, 9.8000e+01, 1.2256e+04,
       1.0000e+00, 0.0000e+00, 3.0000e+00, 0.0000e+00, 0.0000e+00,
       1.5000e+01, 2.0000e+00, 2.0000e+00, 0.0000e+00, 5.0000e+00,
       8.0000e+00, 5.0000e+00, 1.9940e+03, 1.9950e+03, 1.0000e+00,
       1.0000e+00, 6.0000e+00, 6.0000e+00, 1.0000e+00, 1.0000e+00,
       2.0000e+00, 4.0000e+00, 2.0000e+00, 0.0000e+00, 3.0000e+00,
       0.0000e+00, 2.0000e+00, 5.0000e+00, 0.0000e+00, 1.0000e+00,
       3.0000e+00, 1.0000e+00, 2.0000e+00, 9.0000e+00, 6.0000e+00,
       2.0000e+00, 4.0000e+00, 1.0000e+00, 1.0000e+00, 2.0000e+00,
       7.1200e+02, 4.0000e+00, 2.0000e+00, 0.0000e+00, 4.0000e+00,
       2.0100e+03, 4.0000e+00, 4.0850e+03, 3.0000e+00, 3.2000e+01,
       3.5000e+00])

In [69]:
df1

      Unnamed: 0  MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  LandContour  LotConfig  LandSlope  Neighborhood  Condition1  Condition2  BldgType  HouseStyle  OverallQual  OverallCond  YearBuilt  YearRemodAdd  RoofStyle  RoofMatl  Exterior1st  Exterior2nd  MasVnrType  MasVnrArea  ExterQual  ExterCond  Foundation  BsmtQual  BsmtCond  BsmtExposure  BsmtFinType1  BsmtFinType2  HeatingQC  CentralAir  BedroomAbvGr  KitchenAbvGr  KitchenQual  TotRmsAbvGrd  Functional  Fireplaces  FireplaceQu  GarageType  GarageFinish  GarageCars  GarageArea  GarageCond  PavedDrive  PoolArea  MoSold  YrSold  SaleCondition  TotalSF  TotalBath  TotalPorchSF  TotalBathSum  SalePrice
892          892          20         3         70.0     8414       1         3            3          4          0            19           2           2         0           2            6            8       1963          2003          3         1            6            6           2           2          3          4           1         3         3             3             2             5          4           1             3             1            3             6           6           0            2           1             1           1         264           4           2         0       2    2006              4     2127          1             0           1.5     154500
1105        1105          60         3         98.0    12256       1         0            3          0          0            15           2           2         0           5            8            5       1994          1995          1         1            6            6           1           1          2          4           2         0         3             0             2             5          0           1             3             1            2             9           6           2            4           1             1           2         712           4           2         0       4    2010              4     4085          3            32           3.5     325000
413          413          30         4         56.0     8960       1         3            3          4          0            17           0           2         0           2            5            6       1927          1950          1         1           14           15           2           2          3          4           1         3         3             3             5             5          2           1             2             1            3             5           6           1            2           5             2           2         360           4           2         0       3    2010              4     2036          1           130           1.0     115000
522          522          50         4         50.0     5000       1         3            3          0          0             3           1           2         0           0            6            7       1947          1950          1         1            5            5           2           2          3          2           1         3         3             3             0             5          0           1             3             1            3             7           6           2            2           5             2           2         420           4           2         0      10    2006              4     2668          2            60           2.0     159000
1036        1036          20         3         89.0    12898       1         0            1          4          0            23           2           2         0           2            9            5       2007          2008          3         1           12           13           3           3          2          4           2         0         3             1             2             5          0           1             2             1            0             6           6           1            0           1             0           3         912           4           2         0       9    2009              4     3240          2             0           3.0     315500
...          ...         ...       ...          ...      ...     ...       ...          ...        ...        ...           ...         ...         ...       ...         ...          ...          ...        ...           ...        ...       ...          ...          ...         ...         ...        ...        ...         ...       ...       ...           ...           ...           ...        ...         ...           ...           ...          ...           ...         ...         ...          ...         ...           ...         ...         ...         ...         ...       ...     ...     ...            ...      ...        ...           ...           ...        ...
1095        1095          20         3         78.0     9317       1         0            3          4          0             5           2           2         0           2            6            5       2006          2006          1         1           12           13           2           2          2          4           2         2         3             3             2             5          2           1             3             1            2             6           6           1            2           1             1           2         440           4           2         0       3    2007              4     2628          2            22           2.0     176432
1130        1130          50         3         65.0     7804       1         3            3          4          0            18           2           2         0           0            4            3       1928          1950          1         1           14           10           2           2          3          4           0         3         3             3             1             5          4           1             4             1            2             7           3           2            4           5             2           2         576           4           2         0      12    2009              4     3103          2            44           3.0     135000
1294        1294          20         3         60.0     8172       1         3            3          4          0             7           2           2         0           2            5            7       1955          1990          3         1           14           10           2           2          3          4           1         3         3             3             4             5          4           1             2             1            3             5           6           0            2           5             2           2         572           4           0         0       4    2006              4     1728          1             0           2.0     115000
860          860          50         3         55.0     7642       1         3            3          0          0             6           2           2         0           0            7            8       1918          1998          1         1           13           14           2           2          2          4           0         3         3             3             5             5          2           1             3             1            2             7           6           1            2           5             2           1         216           4           2         0       6    2007              4     2338          2           240           1.5     189950
1126        1126         120         3         53.0     3684       1         3            3          4          0             0           2           2         4           2            7            5       2007          2007          3         1           12           13           1           1          2          4           2         2         3             3             5             5          0           1             2             1            2             7           6           1            4           1             0           3         660           4           2         0       6    2009              4     2928          2            20           2.0     174000

[1460 rows x 57 columns]

In [72]:
model.predict(X1)[5]

66163.83575312304